try:
    result = 445/0

except:
    print('Erron Found')

finally:
    print('Finaly Here')

print ('Done')